package folk.sisby.switchy.api;

import net.minecraft.nbt.NbtCompound;

/**
 * @author Sisby folk
 * @since 2.0.0
 * Represents any object that can be crushed down to and reconstituted from NBT Compounds.
 */
public interface SwitchySerializable {
	/**
	 * Serializes the contents of this object.
	 *
	 * @return an arbitrary NBT Compound representing this object.
	 */
	NbtCompound toNbt();

	/**
	 * Deserializes an NBT compound and populates this object with it.
	 *
	 * @param nbt An NBT compound previously generated by {@link SwitchySerializable#toNbt} or equivalent.
	 */
	void fillFromNbt(NbtCompound nbt);
}
