plugins {
	id "maven-publish"
	alias libs.plugins.githubRelease
	alias libs.plugins.minotaur
}

githubRelease {
	token = "$System.env.GITHUB_TOKEN"
	owner = project.user
	repo = slug
	tagName = "v${baseVersion}+${tagBranch}"
	targetCommitish = tagBranch
	releaseAssets = remapJar
	releaseName = "v${baseVersion}"
	allowUploadToExisting = true
	generateReleaseNotes = true
	body = !file("CHANGELOG.md").exists() ? "" : rootProject.file("CHANGELOG.md").text
}

modrinth {
	token = "$System.env.MODRINTH_TOKEN"
	projectId = slug
	versionNumber = project.version
	uploadFile = remapJar
	gameVersions = compatibleVersions.split(", ").toList()
	loaders = compatibleLoaders.split(", ").toList()
	changelog = !file("CHANGELOG.md").exists() ? "" : rootProject.file("CHANGELOG.md").text + "\n\nChangelog: https://github.com/${user}/${slug}/releases/tag/v${baseVersion}+${tagBranch}"
	syncBodyFrom = rootProject.file("README.md").text
	dependencies {
		required.version libs.fapi.get().getName(), libs.versions.fapi.get()
		optional.version libs.owo.get().getName(), libs.versions.owo.get()
		optional.version libs.drogtor.get().getName(), libs.versions.drogtor.get()
		optional.version libs.fabrictailor.get().getName(), libs.versions.fabrictailor.get()
		optional.version libs.pehkui.get().getName(), libs.versions.pehkui.get()
		optional.version libs.origins.get().getName(), libs.versions.origins.get()
		optional.version libs.fabrication.get().getName(), libs.versions.fabrication.get()
		optional.version libs.styledNicknames.get().getName(), libs.versions.styledNicknames.get()
		optional.version libs.figura.get().getName(), libs.versions.figura.get()
	}
}

tasks.register("fullRelease") {
	group "publishing"
	dependsOn "githubRelease"
	dependsOn "modrinth"
	dependsOn "publish"
}

