# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=folk.sisby
user=sisby-folk
slug=switchy
modId=switchy
modName=Switchy
modDescription=Player presets that change nothing - including display name, skin, origin, inventory, and more!
authors=Sisby folk
contributors=Garden System, MerchantPug, Ampflower, solonovamax, Ami, SilverAndro
license=LGPL-3.0-or-later
# Submodule Metadata
coreId=switchy-core
coreName=Switchy Core
coreDescription=Server-side player presets, with API and commands
clientId=switchy-client
clientName=Switchy Client
clientDescription=Networking for switchy, with a client-side API and commands
cardinalId=switchy-cardinal
cardinalName=Switchy Cardinal
cardinalDescription=Data-driven Switchy modules for CCA components
uiId=switchy-ui
uiName=Switchy UI
uiDescription=GUI for managing player presets via Switchy Client
compatId=switchy-compat
compatName=Switchy Compat
compatDescription=Switchy modules for player personalization mods
cardinalUiId=switchy-cardinal-ui
cardinalUiName=Switchy Cardinal UI
cardinalUiDescription=Data-driven UI previews for CCA Switchy modules
compatUiId=switchy-compat-ui
compatUiName=Switchy Compat UI
compatUiDescription=UI previews for Switchy Compat modules for Switchy UI
# Mod Version
baseVersion=2.9.6
# Branch Metadata
branch=1.19
tagBranch=1.19
compatibleVersions=1.19.2
compatibleLoaders=fabric, quilt
