# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=io.github.username
user=username
slug=mod-id
modId=mod_id
modName=Mod ID
modDescription=Sal doesn't have editing software so he has to make memes through minecraft mod descriptions, making him tonight's big loser.
authors=Anonymous
contributors=all this mod's adoring fans!
license=MIT
# Mod Version
modVersion=0.1.0
# Branch Metadata
branchName=fabric-1.21
compatibleVersions=1.21.1
compatibleLoaders=fabric
