# Gradle
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
# Mod Metadata
group=dev.sisby
user=sisby-folk
slug=switchy
modId=switchy
modName=Switchy
modDescription=RPG-style character switching for minecraft!
authors=Sisby folk
contributors=
license=EUPL-1.2
# Mod Version
modVersion=3.0.0-beta.1
# Branch Metadata
branchName=1.21
compatibleVersions=1.21.1
compatibleLoaders=fabric, quilt, forge
