[versions]
loom = "1.2.+"
githubRelease = "2.4.1"
minotaur = "2.6.0"

mc = "1.19.3"
ql = "0.19.0"
qm = "1.19.3+build.28"
fapi = "0.76.0-1.19.3"
qfapi = "5.0.0-beta.9+0.76.0-1.19.3"
serverTranslationsApi = "1.4.19+1.19.3"
kaleidoConfig = "0.1.0+1.1.0-beta.3"

owo = "0.10.3+1.19.3"

cardinal = "5.0.2"

drogtor = "1.1.3+1.19"
fabrictailor = "2.0.2"
origins = "v1.8.1"
apoli = "v2.7.1"
calio = "1.9.0"
pehkui = "3.7.5"
fabrication = "3.2.7+1.19.3"
styledNicknames = "1.2.0+1.19.3"
placeholder = "2.0.0-rc.1+1.19.3"
playerData = "0.2.2+1.19.3"
luaj = "3.0.6-figura"
figura = "0.1.2"

[plugins]
loom = { id = "org.quiltmc.loom", version.ref = "loom" }
githubRelease = { id = "com.github.breadmoirai.github-release", version.ref = "githubRelease" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
mc = { group = "mojang", name = "minecraft", version.ref = "mc" }
ql = { group = "org.quiltmc", name = "quilt-loader", version.ref = "ql" }
qm = { group = "org.quiltmc", name = "quilt-mappings", version.ref = "qm" }
qfapi = { group = "org.quiltmc.quilted-fabric-api", name = "quilted-fabric-api", version.ref = "qfapi" }
serverTranslationsApi = { group = "fr.catcore", name = "server-translations-api", version.ref = "serverTranslationsApi" }
kaleidoConfig = { group = "folk.sisby", name = "kaleido-config", version.ref = "kaleidoConfig" }

owo = { group = "io.wispforest", name = "owo-lib", version.ref = "owo" }

cardinal = { group = "dev.onyxstudios.cardinal-components-api", name = "cardinal-components-base", version.ref = "cardinal" }

drogtor = { group = "maven.modrinth", name = "drogtor", version.ref = "drogtor" }
fabrictailor = { group = "maven.modrinth", name = "fabrictailor", version.ref = "fabrictailor" }
origins = { group = "com.github.apace100", name = "origins-fabric", version.ref = "origins" }
apoli = { group = "com.github.apace100", name = "apoli", version.ref = "apoli" }
calio = { group = "com.github.apace100", name = "calio", version.ref = "calio" }
pehkui = { group = "com.github.Virtuoel", name = "Pehkui", version.ref = "pehkui" }
fabrication = { group = "maven.modrinth", name = "fabrication", version.ref = "fabrication" }
styledNicknames = { group = "maven.modrinth", name = "styled-nicknames", version.ref = "styledNicknames" }
placeholder = { group = "eu.pb4", name = "placeholder-api", version.ref = "placeholder" }
playerData = { group = "eu.pb4", name = "player-data-api", version.ref = "playerData" }
luaj = { group = "com.github.Kingdom-of-The-Moon.luaj", name = "luaj-core", version.ref = "luaj" }
figura = { group = "com.github.FiguraMC", name = "Figura", version.ref = "figura" }
