[versions]
loom = "1.3.+"
githubRelease = "2.4.1"
minotaur = "2.6.0"

mc = "1.18.2"
ql = "0.19.0"
qm = "1.18.2+build.26"
fapi = "0.67.0-1.18.2"
qfapi = "1.0.0-beta.28+0.67.0-1.18.2"
serverTranslationsApi = "1.4.12+1.18.2"
kaleidoConfig = "0.1.0+1.1.0-beta.3"

owo = "0.9.3+1.19"

cardinal = "4.2.0"

drogtor = "1.1.3"
fabrictailor = "1.9.0"
origins = "v1.4.1"
apoli = "v2.3.3"
calio = "-SNAPSHOT"
pehkui = "3.4.2"
fabrication = "3.0.2+1.18"
styledNicknames = "1.0.4+1.18.1"
placeholder = "1.1.3+1.17.1"
playerData = "0.1.0+1.18"
luaj = "3.0.6-figura"
figura = "0.1.2"

[plugins]
loom = { id = "org.quiltmc.loom", version.ref = "loom" }
githubRelease = { id = "com.github.breadmoirai.github-release", version.ref = "githubRelease" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
mc = { group = "mojang", name = "minecraft", version.ref = "mc" }
ql = { group = "org.quiltmc", name = "quilt-loader", version.ref = "ql" }
qm = { group = "org.quiltmc", name = "quilt-mappings", version.ref = "qm" }
qfapi = { group = "org.quiltmc.quilted-fabric-api", name = "quilted-fabric-api", version.ref = "qfapi" }
serverTranslationsApi = { group = "fr.catcore", name = "server-translations-api", version.ref = "serverTranslationsApi" }
kaleidoConfig = { group = "folk.sisby", name = "kaleido-config", version.ref = "kaleidoConfig" }

owo = { group = "io.wispforest", name = "owo-lib", version.ref = "owo" }

cardinal = { group = "dev.onyxstudios.cardinal-components-api", name = "cardinal-components-base", version.ref = "cardinal" }

drogtor = { group = "maven.modrinth", name = "drogtor", version.ref = "drogtor" }
fabrictailor = { group = "maven.modrinth", name = "fabrictailor", version.ref = "fabrictailor" }
origins = { group = "com.github.apace100", name = "origins-fabric", version.ref = "origins" }
apoli = { group = "com.github.apace100", name = "apoli", version.ref = "apoli" }
calio = { group = "com.github.LambdAurora", name = "calio-test", version.ref = "calio" }
pehkui = { group = "com.github.Virtuoel", name = "Pehkui", version.ref = "pehkui" }
fabrication = { group = "maven.modrinth", name = "fabrication", version.ref = "fabrication" }
styledNicknames = { group = "maven.modrinth", name = "styled-nicknames", version.ref = "styledNicknames" }
placeholder = { group = "eu.pb4", name = "placeholder-api", version.ref = "placeholder" }
playerData = { group = "eu.pb4", name = "player-data-api", version.ref = "playerData" }
luaj = { group = "com.github.Kingdom-of-The-Moon.luaj", name = "luaj-core", version.ref = "luaj" }
figura = { group = "com.github.FiguraMC", name = "Figura", version.ref = "figura" }
